<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>net48</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RunPostBuildEvent>Always</RunPostBuildEvent>
	</PropertyGroup>

	<PropertyGroup>
		<DisableFastUpToDateCheck Condition="$(Configuration.Contains(&quot;Release&quot;))">true</DisableFastUpToDateCheck>
	</PropertyGroup>

	<PropertyGroup>
		<!-- インストール時のUACに表示される名前 -->
		<Gekka_SignTool_Description>Setup TestDescription</Gekka_SignTool_Description>
	</PropertyGroup>
	<Target Name="SignSetup1" BeforeTargets="Build">
		<ItemGroup>
			<Gekka_SignTool_InputFiles Include="..\Setup1\Release\*" />
		</ItemGroup>
	</Target>
</Project>
