<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<!--<TargetFrameworks>net48;net8.0</TargetFrameworks>-->
		<TargetFrameworks>netstandard1.0</TargetFrameworks>
		<OutputType>Library</OutputType>


		<Configurations>Release;Degug</Configurations>
		<PackageVersion>0.0.0.0</PackageVersion>

		<!-- <SignTool_Algorithm_SHA1>false</SignTool_Algorithm_SHA1> -->
		<!-- <SignTool_Algorithm_SHA256>true</SignTool_Algorithm_SHA256> -->
		<DisableFastUpToDateCheck Condition="$(Configuration.Contains(&quot;Release&quot;))">true</DisableFastUpToDateCheck>
	</PropertyGroup>

	<Target Name="SignTool_CleanTestFiles" AfterTargets="Clean" DependsOnTargets="Clean">
		<ItemGroup>
			<SignTool_Delete_Files Include="bin\TestInputFiles\*" />
		</ItemGroup>

		<Delete Files="%(SignTool_Delete_Files.FullPath)" />
	</Target>

	<Target Name="SignTool_CopyTestFiles" BeforeTargets="BeforeBuild">
		<Message Importance="low" Text="Copy Test Files from zip" />
		
		<Unzip SourceFiles="TestInputFiles\TestFiles.zip" DestinationFolder="$(ProjectDir)\bin\TestInputFiles\"  />
		<ItemGroup>
			<!-- 実際にSignToolに渡して署名するファイルを登録 -->
			<SignTool_InputFiles Include="bin\TestInputFiles\*"  />
		</ItemGroup>
	</Target>

</Project>
